os:
  - linux
  - osx
sudo: false
env:
  matrix:
  - TRAVIS_NODE_VERSION="11"
  - TRAVIS_NODE_VERSION="10"
  - TRAVIS_NODE_VERSION="9"
  - TRAVIS_NODE_VERSION="8"
  - TRAVIS_NODE_VERSION="7"
  - TRAVIS_NODE_VERSION="6"
  - TRAVIS_NODE_VERSION="5"
  - TRAVIS_NODE_VERSION="4"
  - TRAVIS_NODE_VERSION="0.12"
  - TRAVIS_NODE_VERSION="0.10"
install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - npm --version
  - npm install
script: npm test
